# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d0f2a224ef420996a9bd57ba5a2c51b913dc2be7c7fc5fbcb38ae64f663b0dbd1251610754c870df5e0ddc4ca27bfbe09c5d77c3a33589c9be0c5153a41f6f3

test:
  secret_key_base: f1ff90d81bfee847fdd61cfb9ce60393799ee641c3c8108afaa50cb5bf28030784767f5c68a5d2f1976e301ec14956002e899e0223ea477632bc329cefca153d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
